---
name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    concurrency: main
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: podflow
          pull-request-title-pattern: release${component} ${version}

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-go@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: 1.17

      - name: build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          env GOOS=linux GOARCH=amd64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o bin/podflow-linux-amd64 .
          env GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o bin/podflow-darwin-amd64 .
          env GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o bin/podflow-darwin-arm64 .
          env GOOS=windows GOARCH=amd64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o bin/podflow-windows-amd64.exe .
          # env GOOS=linux GOARCH=arm64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o bin/podflow-linux-arm64 .
          # env GOOS=android GOARCH=amd64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o bin/podflow-android-amd64 .

      - name: upload linux amd64 release binary
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/podflow-linux-amd64
          asset_name: podflow-linux-amd64
          asset_content_type: application/octet-stream
      - name: upload darwin amd64 release binary
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/podflow-darwin-amd64
          asset_name: podflow-darwin-amd64
          asset_content_type: application/octet-stream

      - name: upload darwin arm64 release binary
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/podflow-darwin-arm64
          asset_name: podflow-darwin-arm64
          asset_content_type: application/octet-stream

      - name: upload windows amd64 release binary
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/podflow-windows-amd64.exe
          asset_name: podflow-windows-amd64.exe
          asset_content_type: application/octet-stream
      # - name: upload linux arm64 release binary
      #   if: ${{ steps.release.outputs.release_created }}
      #   uses: actions/upload-release-asset@v1.0.2
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.release.outputs.upload_url }}
      #     asset_path: bin/podflow-linux-arm64
      #     asset_name: podflow-linux-arm64
      #     asset_content_type: application/octet-stream
      # - name: upload android amd64 release binary
      #   if: ${{ steps.release.outputs.release_created }}
      #   uses: actions/upload-release-asset@v1.0.2
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.release.outputs.upload_url }}
      #     asset_path: bin/podflow-android-amd64
      #     asset_name: podflow-android-amd64
      #     asset_content_type: application/octet-stream

  brew:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        if: ${{ needs.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        if: ${{ needs.release.outputs.release_created }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.17

      - name: Run GoReleaser
        if: ${{ needs.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
